# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |provider, override|
    provider.name = "debian8-1024mb"
    override.vm.box = "terminal-labs/tl-debian-8-64bit-30gb"
    override.vm.box_url = "terminal-labs/tl-debian-8-64bit-30gb"
    override.vm.box_version = "0.1"
    provider.customize ['modifyvm', :id, '--nictype1', 'virtio']
    provider.customize ['modifyvm', :id, '--nictype2', 'virtio']
    provider.memory = 1024
  end
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.network "private_network", type: "dhcp"
  # set auto_update to false, if you do NOT want to check the correct
  # additions version when booting this machine
  if Vagrant.has_plugin?("vbguest")
    config.vbguest.auto_update = false
  end
  #config.vm.network :private_network, ip: "172.28.128.128"
end
