# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |provider, override|
    provider.name = "ubuntu14-2048mb"
    override.vm.box = "terminal-labs/tl-ubuntu-1404-64bit-40gb"
    override.vm.box_url = "terminal-labs/tl-ubuntu-1404-64bit-40gb"
    provider.customize ['modifyvm', :id, '--nictype1', 'virtio']
    provider.customize ['modifyvm', :id, '--nictype2', 'virtio']
    provider.memory = 2048
  end
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.network "private_network", type: "dhcp"
end
